name: Build ksu-frida Stealth Module

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Package Magisk KernelSU Module
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch Official Stealth Frida Server
      run: |
        mkdir -p ./bin
        curl -L -o ./bin/frida-server.xz https://github.com/frida/frida/releases/download/16.2.1/frida-server-16.2.1-android-arm64.xz
        xz -d ./bin/frida-server.xz
        chmod +x ./bin/frida-server

    - name: Compress Module layout to Flashable Zip
      run: zip -r ksu-frida-zygisk-stealth.zip . -x "*.git*" "*.github*" "node_modules/*" "*.xz"

    - name: Upload Flashable Module Zip to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ksu-frida-module
        path: ksu-frida-zygisk-stealth.zip
        retention-days: 7